Sku: "SKU1234"
Title: "My Unique Title"
Description: "Description"
StartPrice: "55.67"
Quantity: "Quantity"
ListingType: "Chinese"
Location: "-- not given --"
PrimaryCategory: "98437"
DispatchTimeMax: "3"
ListingDuration: "Days_10"
ShipToLocations:
  - "GB"
  - "World"
  - "Europe"
PictureDetails:
  - GalleryType: "Gallery"
    GalleryURL: ""
    PhotoDisplay: ""
    PictureURL: ""
PaymentMethods:
  - "PayPal"
  - "PersonalCheck"
ShippingServiceOptions:
  - Service: "UK_RoyalMailFirstClassStandard"
    Cost: "1"
    Priority: "1"
  - Service: "UK_RoyalMailSpecialDeliveryNextDay"
    Cost: "6.50"
    Priority: "2"
InternationalShippingServiceOptions:
  - Service: "UK_RoyalMailAirmailInternational"
    Cost: "2.50"
    Priority: "1"
    Location: "Europe"
  - Service: "UK_RoyalMailAirmailInternational"
    Cost: "3.50"
    Priority: "2"
    Location: "Worldwide"
  - Service: "UK_RoyalMailInternationalSignedFor"
    Cost: "8.50"
    Priority: "3"
    Location: "Europe"
  - Service: "UK_RoyalMailInternationalSignedFor"
    Cost: "8.50"
    Priority: "4"
    Location: "Europe"